### ISSUE TITLE
OnePhotonSeries.... (got 'ImagingVolume', expected 'ImagingPlane')

### ISSUE THREAD

**Issue by Charles-Fieseler-Vienna** [focolab/NWBelegans#1]
Hey Daniel! Thanks for all this hard work, I'm really excited to continue with this! I got a small error when running the NWB_tutorial.ipynb with your custom class... not sure if this is a version problem:

---> 67 calcium_image_series = OnePhotonSeries(
     68     name="CalciumImageSeries",
     69     data=wrapped_data,
     70     unit="n/a", 
     71     scan_line_rate = 0.5,
     72     dimension = (650, 900, 22),
     73     rate = 4.0,
     74     imaging_plane = CalcImagingVolume,
     75 )

TypeError: OnePhotonSeries.__init__: incorrect type for 'imaging_plane' (got 'ImagingVolume', expected 'ImagingPlane')

**Comment by dysprague** [comment]
This is a version problem! I updated the NWB tutorial here but still need to publish the update to nix-multichannel-volume. Will do that today.

**Comment by dysprague** [comment]
Okay this should work now if you update ndx-multichannel-volume to version 0.1.2! Lmk if you continue having any issues.

**Comment by Charles-Fieseler-Vienna** [comment]
For future reference, this command fixes it (within the relevant conda environment):

```
pip install --force-reinstall ndx-multichannel-volume
```
