### ISSUE TITLE
Documentation request

### ISSUE THREAD

**Issue by Charles-Fieseler-Vienna** [focolab/NWBelegans#2]
Can you document the expected format of "gce_quant" in cell 11 of NWB_tutorial.ipynb?

I think it's a long single-level dataframe that must have an object for each ID for each time point. Is that enough? Is 'ID' a neuropal ID?

**Comment by dysprague** [comment]
Yes this is a long single-level data frame where each row contains the position, ID, and quant information for each blob at each time point. The ID information is optional. The way this is set up currently assumes that every blob exists in every time point (this is the result of a tracking algorithm for blobs across time points), but I'm now realizing that that is probably not the best assumption so will make a clarification and add an issue here to update that.

I added some documentation on this but also added a box link to download all of the data that we use in this tutorial so folks can explore the data themselves.

'ID' refers to the cell ID, e.g. 'IL1VR', 'ALA', etc. This is the same as the NeuroPAL IDs but is just the cell names is non specific to NeuroPAL. You would most likely do some sort of tracking algorithm between your NeuroPAL structural image and your calcium images to assign these cell IDs to your calcium activity traces.

**Comment by Charles-Fieseler-Vienna** [comment]
Thanks!
