### ISSUE TITLE
Best practice for green and red channels (images and traces)

### ISSUE THREAD

**Issue by Charles-Fieseler-Vienna** [focolab/NWBelegans#3]
Besides the metadata, I think the top-level name of the objects are important. I'm referring to cell 10 in the tutorial:

```
calcium_image_series = OnePhotonSeries(
    name="CalciumImageSeries",
    data=wrapped_data,
    unit="n/a", 
    scan_line_rate = 0.5,
    dimension = [1000,240,12],
    rate = 4.0,
    imaging_plane = CalcImagingVolume,
)
```

And cell 11:

```

fluor = Fluorescence(
    name = 'CalciumFluorTimeSeries',
    roi_response_series = RoiResponse
)
```

Are there standardized names for green (gcamp) vs red (mscarlet/mcherry/mneptune)?

Proposal:
CalciumImageSeries -> SignalCalciumImageSeries + ReferenceCalciumImageSeries
CalciumFluorTimeSeries -> SignalCalciumFluorTimeSeries + ReferenceCalciumFluorTimeSeries

Then should we add a third Fluorescence object for the processed time series (which isn't just df/f)?

Proposal:
ProcessedCalciumFluorTimeSeries or FinalCalciumFluorTimeSeries

**Comment by dysprague** [comment]
Yes that is a good callout! The images that we're taking in our lab don't use a reference set (I might be wrong but I think that's usually more relevant for freely moving datasets), but I agree for the sake of standardization we should make that clear. I'll add some placeholder values for those and I like your suggested names!

**Comment by dysprague** [comment]
I just committed a new version of the code where the Calcium images are stored as a MultiChannelVolumeSeries object. This object allows you to store multiple channels of volumetric time series data. I thought it would be best to just store the signal and reference channels in one file and then add a comment on which channel maps to signal vs reference. I also add placeholders for the reference fluorescence and processed fluorescence.

Let me know if this works! You'll also have to update ndx-multichannel-volume to 0.1.3 to use the MultiChannelVolumeSeries object

**Comment by Charles-Fieseler-Vienna** [comment]
That sounds good to me! When you say "add a comment" I assume we also need to standardize that? I'll check it out!

**Comment by dysprague** [comment]
The comment is a free form message. It shouldn't affect anything about how you use the NWB file, but can be printed. I'm not sure we should be overly prescriptive on what to include in the comments cause different groups may have a different number of channels or use different fluorophores. The OpticalChannels objects will be named based on the fluorophore used for that channel and I think for the most part GFP-GCaMP will be the GCaMP signal and some red fluorophore will be the reference channel. I think it should be sufficient to allow free form comment with some guidelines. I put an example comment in the tutorial.

**Comment by Charles-Fieseler-Vienna** [comment]
Some part for free form comments is great for sure... but something should be standardized around signal vs. reference. For now it's probably easiest to do RGB -> Reference-Signal-empty, so that's what I'll do
