### ISSUE TITLE
Gce_quant in tutorial assumes all blobs exist at all time points

### ISSUE THREAD

**Issue by dysprague** [focolab/NWBelegans#4]
The way we are currently adding blobs to the volume segmentation for Calcium time series in the NWB tutorial assumes that all blobs indexes exist at all time points (results of a complete tracking algorithm). This could screw up the ordering in each volume segmentation if this assumption is false.

Should possibly add some placeholder values indicated non-existent blobs at a specific time point to ensure ordering stays consistent.

**Comment by Charles-Fieseler-Vienna** [comment]
My initial format is a square-ish dataframe (t x num_neurons), and pandas adds nan by default for missing rows. Converting from this format to your long one is easy with stack() in pandas

I know there are many ways to solve this, but that's how I've been solving it

**Comment by Charles-Fieseler-Vienna** [comment]
I got significantly further this time, with a partially written file! However, I think it crashes at the first nan point in the tracking due to typecasting. I'm not explicitly casting anything as int, so I guess it's assumed in one of these datatypes. I think for missing tracking, each object would need nan (calcium imaging series and segmentation)

 The error is quite long and obscure so I'll just copy the end.:

ValueError: cannot convert float NaN to integer

**Comment by dysprague** [comment]
I'll try to take a look at this this weekend and brainstorm a solution! Would you be able to send a saved version of the data frame you're using and some code to recreate the issue?

**Comment by Charles-Fieseler-Vienna** [comment]
I sent an email with the .h5 file, which should be a drop-in replacement for your gce_quant file

**Comment by dysprague** [comment]
NWB does expect segmentation results to be integers. This is because when defining a region of interest, you should include the specific voxels that include the ROI and voxel indexes will always be integers. I think it makes sense to keep it that way because if you wanted to extract any data from the images using the segmentation, you would need the integer indexes anyways. 

For now, I got around the NaN -> integer conversion problem by just replacing any rows with NaN values with a row of [0,0,0] and weight 0 indicating that this row is a missing value.

**Comment by dysprague** [comment]
Closing this issue for now but feel free to reopen/create another issue if this solution does not work for you
